# 警告:本文件由 tools/cw/gen_plaza_invest.py 生成(plaza config V4.4),勿手编;
# 版本更新重跑生成;人工建模增量(economy/评估分/分类)在 cw_investments.py。
# 人读版(同源生成,品质分组表格): docs/game/currency_war/data/invest_cards.md
# 重跑: uv run python tools/cw/gen_plaza_invest.py
"""货币战争 投资策略/环境 base 数据(plaza 官方 API,gen_plaza_invest.py 生成)。

投资策略(fight_augment_list)334 条 / 投资环境(portal_list)83 条,V4.4。
数字 id 为稳定主键;name 已 canon 归一(注册表键);effect 为官方效果全文(去富文本)。
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PlazaAugment:
    """投资策略 base 条目(局内 3 选 1,可刷新)。"""
    id: str      # plaza 稳定 id(fight_augment_list.id)
    name: str    # canon 归一名(注册表键)
    rarity: str  # 棱彩/金/银(quality 3/2/1)
    effect: str  # 官方效果全文


@dataclass(frozen=True)
class PlazaPortal:
    """投资环境 base 条目(开局/固定节点 3 选 1)。"""
    id: str
    name: str
    effect: str


PLAZA_AUGMENTS: tuple[PlazaAugment, ...] = (
    PlazaAugment(id='100101', name='特战资金', rarity='银', effect='进入首领节点时，获得7枚金币。'),
    PlazaAugment(id='100102', name='特战资金+', rarity='银', effect='进入首领节点时，获得11枚金币。'),
    PlazaAugment(id='100201', name='经验到账', rarity='银', effect='获得10经验值。'),
    PlazaAugment(id='100301', name='免费午餐', rarity='银', effect='获得11次免费刷新。'),
    PlazaAugment(id='100401', name='二费援军', rarity='银', effect='获得4个随机2费角色。'),
    PlazaAugment(id='100402', name='三费援军', rarity='银', effect='获得4个随机3费角色。'),
    PlazaAugment(id='100403', name='四费援军', rarity='银', effect='获得4个随机4费角色。'),
    PlazaAugment(id='100501', name='存款回报', rarity='银', effect='每次进入新节点时，如果在上个节点没有花费金币，则获得2次免费刷新。'),
    PlazaAugment(id='100601', name='尾款交付', rarity='银', effect='进入最后一个补给阶段后，获得30金币。'),
    PlazaAugment(id='100701', name='打捞人才库', rarity='银', effect='每次进入补给阶段后，随机获得一个未被选择的角色及其携带的装备。'),
    PlazaAugment(id='100702', name='打捞人才库+', rarity='银', effect='每次进入补给阶段后，随机获得一个未被选择的角色及其携带的装备。获得1个随机简易装备和4金币。'),
    PlazaAugment(id='100901', name='胜利,还是胜利', rarity='银', effect='使当前连胜数变为4。获得4金币。'),
    PlazaAugment(id='101001', name='全队的希望', rarity='银', effect='处在前台1号位的我方角色获得15%伤害增幅和15%生命增幅。'),
    PlazaAugment(id='101101', name='黄金期货', rarity='银', effect='5个节点后，进行一次不能刷新的黄金投资策略三选一。'),
    PlazaAugment(id='101102', name='黄金期货+', rarity='银', effect='4个节点后，进行一次不能刷新的黄金投资策略三选一。'),
    PlazaAugment(id='101201', name='返利', rarity='银', effect='每购买3个5费角色，获得3金币。'),
    PlazaAugment(id='101202', name='返利+', rarity='银', effect='每购买3个5费角色，获得3金币。立刻获得6金币。'),
    PlazaAugment(id='101301', name='规模效应', rarity='银', effect='首次拥有8个一样的角色时，获得1个【完美投影仪】。'),
    PlazaAugment(id='101401', name='军火贸易', rarity='银', effect='获得1个【简易武装箱】，获得4金币。'),
    PlazaAugment(id='101402', name='军火贸易+', rarity='银', effect='获得1个【简易武装箱】，获得8金币。'),
    PlazaAugment(id='101501', name='以战养战', rarity='银', effect='在遭遇节点战斗后，获得1个【简易武装箱】。获得6金币。'),
    PlazaAugment(id='101601', name='人才激励', rarity='银', effect='获得1个【员工投影仪】，4个节点后，获得1个【员工投影仪】。'),
    PlazaAugment(id='101602', name='人才激励+', rarity='银', effect='获得1个【员工投影仪】，3个节点后，获得1个【员工投影仪】。'),
    PlazaAugment(id='101701', name='成长基金', rarity='银', effect='在你到达9级时，提供40金币。'),
    PlazaAugment(id='101801', name='武力刷新', rarity='银', effect='合成装备时，获得2次刷新。'),
    PlazaAugment(id='101901', name='节省工位', rarity='银', effect='在接下来3个节点只有3个备战席位置。随后，获得3件简易装备。'),
    PlazaAugment(id='102001', name='躺平', rarity='银', effect='你无法在商店购买角色和刷新，持续3个节点。在此之后，获得20金币。'),
    PlazaAugment(id='102101', name='公司人才流动', rarity='银', effect='每次进入新节点时，处在备战席最右侧3个位置的角色变为随机的同费用角色。获得2金币。'),
    PlazaAugment(id='102201', name='市场干预', rarity='银', effect='下一次和每4次商店刷新都将是全3费角色。获得5次刷新。'),
    PlazaAugment(id='102301', name='恢复生机', rarity='银', effect='最终首领战结束时，回复40点小队生命值。'),
    PlazaAugment(id='102401', name='扩充团队', rarity='银', effect='获得2个1费角色，2个2费角色和1个3费角色。'),
    PlazaAugment(id='102501', name='武装支援', rarity='银', effect='获得1件随机简易装备和2个随机3费角色。'),
    PlazaAugment(id='102502', name='武装支援+', rarity='银', effect='获得1件随机简易装备和1个随机4费角色，获得6金币。'),
    PlazaAugment(id='102601', name='爆晶矿·银', rarity='银', effect='我方小队消灭敌方目标时，有20%概率获得一个战利品晶矿。'),
    PlazaAugment(id='102701', name='全员晋升', rarity='银', effect='场上的所有角色会永久升级成比自身高1费的随机角色(最大5费)。获得2个【拆装扳手】。'),
    PlazaAugment(id='102801', name='人力重组', rarity='银', effect='出售场上和备战席的所有角色。获得1个随机的2星3费角色、2个2星2费角色和2个2星1费角色。'),
    PlazaAugment(id='102901', name='合并同类项', rarity='银', effect='刷新商店时，若刷新的角色中出现2个相同的角色，获得1金币。获得4次免费刷新。'),
    PlazaAugment(id='103001', name='无伤通关', rarity='银', effect='战斗结束时，若此次战斗中没有角色陷入过无法战斗状态，获得1金币。立即获得1个【生命之花】。'),
    PlazaAugment(id='103101', name='招聘资金', rarity='银', effect='获得2张3费聘用书，获得4金币。'),
    PlazaAugment(id='103102', name='招聘资金+', rarity='银', effect='获得2张4费聘用书，获得5金币。'),
    PlazaAugment(id='103201', name='气氛组', rarity='银', effect='战斗结束时，每有2名伤害统计中造成伤害为0的角色，获得1经验。'),
    PlazaAugment(id='103202', name='气氛组+', rarity='银', effect='战斗结束时，每有2名伤害统计中造成伤害为0的角色，获得1经验。获得8经验。'),
    PlazaAugment(id='103301', name='健康充值', rarity='银', effect='获得30点小队生命和30点小队生命上限。'),
    PlazaAugment(id='103401', name='溜佩佩', rarity='银', effect='获得9金币，什么都没带的佩佩会在你的后排逛街，让小队获得1%前/后台强度。'),
    PlazaAugment(id='103402', name='溜佩佩+', rarity='银', effect='获得15金币，什么都没带的佩佩会在你的后排逛街，让小队获得1%前/后台强度。'),
    PlazaAugment(id='103501', name='招财狗', rarity='银', effect='获得一个佩佩。战斗胜利后，若未损失小队生命值，则每有一个佩佩就会为你提供1金币。'),
    PlazaAugment(id='103601', name='经验就是财富', rarity='银', effect='获得经验时，改为获取等量金币（购买经验除外）。获得4金币。'),
    PlazaAugment(id='103701', name='成长的快乐', rarity='银', effect='升到8级后，你购买经验所需的金币降低1金币。立刻获得4经验。'),
    PlazaAugment(id='103802', name='二极管', rarity='银', effect='本场对局中，你的遭遇节点只有最低和最高两个难度；获得10小队生命值和生命上限，获得6金币。'),
    PlazaAugment(id='103901', name='免费升舱', rarity='银', effect='本场对局中，你的遭遇奖励提高1级（遭遇4也能获得额外奖励）。立刻获得4金币。'),
    PlazaAugment(id='104001', name='星星相印', rarity='银', effect='每次合成3星角色时，获得5金币。立刻获得1个【员工投影仪】。'),
    PlazaAugment(id='110101', name='买彩票', rarity='银', effect='获得1个随机星徽。'),
    PlazaAugment(id='110102', name='买彩票+', rarity='银', effect='获得1个随机星徽和1个【冶金炉】。'),
    PlazaAugment(id='130101', name='公司军火更新·银', rarity='银', effect='每次进入新节点时，你物品栏里的装备变为同品质的其他装备。获得1件随机简易装备。'),
    PlazaAugment(id='130201', name='许诺特权', rarity='银', effect='在进入7个节点后，获得1个【特权武装箱】。'),
    PlazaAugment(id='130301', name='赌神·银', rarity='银', effect='获得一个【随便骰子】。'),
    PlazaAugment(id='130401', name='钻石商人', rarity='银', effect='升到9级时，获得【财富宝钻】。'),
    PlazaAugment(id='130501', name='保险', rarity='银', effect='每损失20点小队生命值，获得5金币和1个随机简易装备。'),
    PlazaAugment(id='130601', name='自由市场', rarity='银', effect='每当你将要获得一件简易装备时，改为获得1个【简易武装箱】。获得1个随机的简易装备。'),
    PlazaAugment(id='130701', name='先亏后盈', rarity='银', effect='损失20点小队生命值，4个节点后获得2个【简易武装箱】。'),
    PlazaAugment(id='130801', name='精密拆装·银', rarity='银', effect='获得1个【精密拆装扳手】。获得1个随机简易武装。'),
    PlazaAugment(id='130901', name='好运令牌·银', rarity='银', effect='进入3个节点后，获得1个【好运令牌】。'),
    PlazaAugment(id='131001', name='全都要·银', rarity='银', effect='本局游戏中，补给阶段的可选项减少2个。下1个补给阶段选择后，额外获得所有未选择的角色及装备。'),
    PlazaAugment(id='131101', name='是钻石总会发光', rarity='银', effect='2个节点后，获得【红钻】或【蓝钻】。'),
    PlazaAugment(id='131201', name='无害垃圾', rarity='银', effect='获得一个【垃圾袋】并获得8金币。'),
    PlazaAugment(id='150101', name='团队力量·银', rarity='银', effect='每有一个已激活的非独立羁绊，小队就会获得3%前/后台强度。'),
    PlazaAugment(id='150201', name='应援团', rarity='银', effect='进入战斗时，如果后排至少有4个角色，我方小队速度增幅提高15%。'),
    PlazaAugment(id='150301', name='正能量', rarity='银', effect='进入战斗时，我方小队恢复等同于能量上限20%的能量。'),
    PlazaAugment(id='150501', name='完美开局', rarity='银', effect='战斗中，关卡进度小于40%时，我方小队前/后台强度提高40%。'),
    PlazaAugment(id='150601', name='效率员工奖', rarity='银', effect='进入战斗时，速度最高的三名角色及其忆灵速度增幅提高10%。'),
    PlazaAugment(id='150701', name='基层贡献', rarity='银', effect='你的场上每有一个1费角色，我方小队获得3%速度增幅和2%伤害减免。3星1费改为提供3倍。'),
    PlazaAugment(id='150801', name='榜样的力量·银', rarity='银', effect='战斗中，伤害统计排名第一的队员成为【榜样】，前/后台强度提高25%。'),
    PlazaAugment(id='150901', name='当头一棒', rarity='银', effect='每个波次开始时，对生命上限最高的敌方目标造成1000%基础伤害，并使其陷入【脆弱】：受到的伤害提高30%。'),
    PlazaAugment(id='151001', name='简单模式', rarity='银', effect='敌人难度降低3，最多降低至0。'),
    PlazaAugment(id='151101', name='难度修改器', rarity='银', effect='遭遇和首领节点的敌人难度降低4，最多降低至0。'),
    PlazaAugment(id='151201', name='幸运喷雾', rarity='银', effect='我方小队的幸运一击伤害提高25%。'),
    PlazaAugment(id='151301', name='免战牌', rarity='银', effect='进入战斗节点时，直接跳过战斗并进入下一个节点，可生效2次。获得30点经验。'),
    PlazaAugment(id='200101', name='定期福利', rarity='金', effect='立刻获得4个金币，并且在每次进入新节点时，获得2金币。'),
    PlazaAugment(id='200201', name='孪生素数', rarity='金', effect='获得本投资策略后，首次购买1/2/3/4/5费角色时，获得2/3/5/7/11点经验值。'),
    PlazaAugment(id='200301', name='加油站', rarity='金', effect='现在及每次进入新节点时获得1次免费刷新，立刻获得8金币。'),
    PlazaAugment(id='200401', name='价值投资·金', rarity='金', effect='获得1个随机的2星1费角色。每次进入新节点时，获得1星的该角色，补给后额外获得2个，持续至本局游戏结束。'),
    PlazaAugment(id='200501', name='枪在手', rarity='金', effect='立刻获得1件随机简易装备，首领战后，获得1件随机简易装备。'),
    PlazaAugment(id='200502', name='枪在手+', rarity='金', effect='立刻获得2件随机简易装备，首领战后，获得1件随机简易装备。'),
    PlazaAugment(id='200601', name='小复制', rarity='金', effect='获得2个【员工投影仪】。获得7金币。'),
    PlazaAugment(id='200602', name='小复制+', rarity='金', effect='获得2个【员工投影仪】。获得13金币。'),
    PlazaAugment(id='200701', name='延迟收益', rarity='金', effect='在战斗开始100行动值后，我方小队伤害增幅提高40%。'),
    PlazaAugment(id='200801', name='市场活力', rarity='金', effect='商店中有概率出现2星的1费或2费角色，出现概率随等级提升。'),
    PlazaAugment(id='200901', name='不要小看我们的羁绊', rarity='金', effect='当你激活8个羁绊并完成一场战斗后，进入节点时获得5个随机星徽。'),
    PlazaAugment(id='201001', name='星级压制', rarity='金', effect='我方小队获得10%速度增幅，攻击星级低于自身的敌人后，额外造成1次等同于原伤害20%的真实伤害。'),
    PlazaAugment(id='201101', name='彩虹期货', rarity='金', effect='5个节点后，进行一次不能刷新的棱彩投资策略三选一。'),
    PlazaAugment(id='201102', name='彩虹期货+', rarity='金', effect='4个节点后，进行一次不能刷新的棱彩投资策略三选一。'),
    PlazaAugment(id='201201', name='采购专员·金', rarity='金', effect='每7次刷新，商店会刷出5张费用相同的角色，费用为你备战席最左侧角色的费用。'),
    PlazaAugment(id='201301', name='长期主义', rarity='金', effect='现在及接下来3次进入新节点时，每次获得7金币。'),
    PlazaAugment(id='201302', name='长期主义+', rarity='金', effect='现在及接下来3次进入新节点时，每次获得9金币。'),
    PlazaAugment(id='201501', name='砂里淘金', rarity='金', effect='合成2星2费角色时，获得1张【砂金】。'),
    PlazaAugment(id='201601', name='星变', rarity='金', effect='战斗开始时，使一个随机1费角色变为3星。'),
    PlazaAugment(id='201701', name='嘴硬', rarity='金', effect='战斗失败时，受到的小队生命值伤害提高5点，但能维持原来的连胜数。获得6金币。'),
    PlazaAugment(id='201801', name='固定理财', rarity='金', effect='现在以及每个位面开始时，获得4经验值和2次免费刷新。'),
    PlazaAugment(id='201802', name='固定理财+', rarity='金', effect='现在以及每个位面开始时，获得6经验值和3次免费刷新。'),
    PlazaAugment(id='201901', name='市场混乱', rarity='金', effect='在奖励节点的备战阶段，你的商店每4秒进行一次强制刷新，持续7次。'),
    PlazaAugment(id='202001', name='爆晶矿·金', rarity='金', effect='我方小队消灭敌方目标时，有30%概率获得一个战利品晶矿。'),
    PlazaAugment(id='202101', name='大裁员', rarity='金', effect='出售场上和备战席的所有角色，获得双倍价格的金币。获得6次免费刷新。'),
    PlazaAugment(id='202201', name='四费晋升', rarity='金', effect='你购买的下1个4费角色将立刻升到2星。获得12金币。'),
    PlazaAugment(id='202301', name='降本增效', rarity='金', effect='出售场上和备战席的所有角色，获得双倍价格的金币。你接下来6次购买角色是免费的。'),
    PlazaAugment(id='202401', name='空仓', rarity='金', effect='获得1件随机的简易装备。进入新节点时，如果物品栏和备战席没有任何装备(消耗品除外)，则获得2经验值。'),
    PlazaAugment(id='202402', name='空仓+', rarity='金', effect='获得1件随机的简易装备和10经验值。进入新节点时，如果物品栏和备战席没有任何装备(消耗品除外)，则获得2经验值。'),
    PlazaAugment(id='202501', name='超发货币', rarity='金', effect='失去你现在所有的金币，并在5个节点后，获得该金币数+70的总金币。'),
    PlazaAugment(id='202601', name='人才空洞', rarity='金', effect='节点开始时，如果备战席角色小于等于4名，则获得3经验。'),
    PlazaAugment(id='202701', name='人才济济', rarity='金', effect='节点开始时，如果备战席角色大于等于8名，则获得3经验。'),
    PlazaAugment(id='202801', name='剩余价值', rarity='金', effect='战斗结束时，你每剩余30行动值，就会在结算时获得1金币。最多获得4金币。'),
    PlazaAugment(id='202901', name='成本控制', rarity='金', effect='战斗结束时，你每剩余10行动值，就会在结算时回复1点小队生命值。最多获得8小队生命值。立即获得8金币、15点小队生命值和15点生命上限。'),
    PlazaAugment(id='203001', name='五百强', rarity='金', effect='首次有我方队员在战斗中达到500前台或后台强度时，获得30金币。立即获得【折叠小刀】、【和平手枪】。'),
    PlazaAugment(id='203101', name='大扩招', rarity='金', effect='扣除你的金币，每损失4金币，获得一个随机4费角色，最多扣除40金币。获得1个【完美投影仪】和16金币。'),
    PlazaAugment(id='203201', name='白银投资', rarity='金', effect='立刻进行一次白银投资策略三选一，选择有3次刷新机会。3个节点后，再获得一个。'),
    PlazaAugment(id='203301', name='专家招募', rarity='金', effect='获得2个5费聘用书，获得4金币。'),
    PlazaAugment(id='203302', name='专家招募+', rarity='金', effect='获得2个5费聘用书，获得12金币。'),
    PlazaAugment(id='203401', name='按劳分配', rarity='金', effect='战斗中每消耗10个战技点，结算时获得1金币，每场战斗通过该策略最多获得1金币。激活2/4/6/8战技点羁绊时，最多获得2/3/4/6金币。'),
    PlazaAugment(id='203501', name='全都要·金', rarity='金', effect='本局游戏中，补给阶段的可选项减少2个。下2个补给阶段选择后，额外获得所有未选择的角色及装备。'),
    PlazaAugment(id='203601', name='广聚天下英才', rarity='金', effect='获得所有2费角色各一个。'),
    PlazaAugment(id='203701', name='欢愉星徽', rarity='金', effect='获得1个【欢愉星徽】，和1个【绯英】。'),
    PlazaAugment(id='203801', name='艾丝妲的猛犬！', rarity='金', effect='获得一个穿戴【穿刺死棘之枪】的【佩佩】。【穿刺死棘之枪】以400速度行动，造成我方总幸运一击率*2000%的基础伤害。'),
    PlazaAugment(id='203901', name='步狸村之谜', rarity='金', effect='获得一个穿戴【狼狩星徽】的【狸狸】和一个【简易武装箱】。'),
    PlazaAugment(id='204001', name='狸职手续', rarity='金', effect='获得3个穿着1件简易装备的【狸狸】，每2个节点，随机1个【狸狸】会狸开并留下装备。\\n\\n狸职狸会使不是狸职狸的狸也狸职。'),
    PlazaAugment(id='204101', name='双手狸开键盘！', rarity='金', effect='获得【Gemi狸】，它会帮你进行商店和战斗操作！进入新节点时，它会免费刷新商店2次，自动购买你场上拥有的角色。每买到1个角色，【Gemi狸】还会使我方全体获得1%幸运一击率。'),
    PlazaAugment(id='210101', name='列车同行星徽', rarity='金', effect='获得1个【列车同行星徽】，和1个【丹恒·饮月】。'),
    PlazaAugment(id='210301', name='银河学者星徽', rarity='金', effect='获得1个【银河学者星徽】，和1个【艾丝妲】。'),
    PlazaAugment(id='210501', name='贝洛伯格星徽', rarity='金', effect='获得1个【贝洛伯格星徽】，和1个【希儿】。'),
    PlazaAugment(id='210601', name='星间旅人星徽', rarity='金', effect='获得1个【星间旅人星徽】，和1个【银枝】。'),
    PlazaAugment(id='210701', name='仙舟星徽', rarity='金', effect='获得1个【仙舟星徽】，和1个【藿藿】。'),
    PlazaAugment(id='210801', name='狼狩星徽', rarity='金', effect='获得1个【狼狩星徽】，和1个【椒丘】。'),
    PlazaAugment(id='211001', name='盛会之星星徽', rarity='金', effect='获得1个【盛会之星星徽】，和1个【花火】。'),
    PlazaAugment(id='211101', name='昼之半神星徽', rarity='金', effect='获得1个【昼之半神星徽】，和1个【风堇】。'),
    PlazaAugment(id='211201', name='夜之半神星徽', rarity='金', effect='获得1个【夜之半神星徽】，和1个【万敌】。'),
    PlazaAugment(id='211301', name='阿哈大悦', rarity='金', effect='【欢愉】羁绊激活时，阿哈获得40%伤害增幅。从4件简易装备中为阿哈选择1件，祂的羁绊简易装备全部变为该简易装备，获得1个【简易武装箱】。\\n\\n阿哈已合成的进阶装备会被拆散，你提供的那件简易装备会回到你的装备栏。'),
    PlazaAugment(id='211401', name='命运圣杯星徽', rarity='金', effect='获得1个【命运圣杯星徽】，和1个【远坂凛】。'),
    PlazaAugment(id='220101', name='追击星徽', rarity='金', effect='获得1个【追击星徽】，和1个【飞霄】。'),
    PlazaAugment(id='220201', name='击破星徽', rarity='金', effect='获得1个【击破星徽】，和1个【阮·梅】。'),
    PlazaAugment(id='220301', name='群攻星徽', rarity='金', effect='获得1个【群攻星徽】，和1个【翡翠】。'),
    PlazaAugment(id='220401', name='能量星徽', rarity='金', effect='获得1个【能量星徽】，和1个【星期日】。'),
    PlazaAugment(id='220501', name='治疗星徽', rarity='金', effect='获得1个【治疗星徽】，和1个【风堇】。'),
    PlazaAugment(id='220601', name='燃血星徽', rarity='金', effect='获得1个【燃血星徽】，和1个【万敌】。'),
    PlazaAugment(id='220701', name='减益星徽', rarity='金', effect='获得1个【减益星徽】，和1个【黄泉】。'),
    PlazaAugment(id='220801', name='持续伤害星徽', rarity='金', effect='获得1个【持续伤害星徽】，和1个【卡芙卡】。'),
    PlazaAugment(id='220901', name='量子同频星徽', rarity='金', effect='获得1个【量子同频星徽】，和1个【希儿】。'),
    PlazaAugment(id='221001', name='护盾星徽', rarity='金', effect='获得1个【护盾星徽】，和1个【砂金】。'),
    PlazaAugment(id='221101', name='战技点星徽', rarity='金', effect='获得1个【战技点星徽】，和1个【丹恒·饮月】。'),
    PlazaAugment(id='230101', name='幸运星祝福', rarity='金', effect='获得1个【幸运星】。我方小队获得15%幸运一击率和5%速度增幅。'),
    PlazaAugment(id='230201', name='折叠小刀祝福', rarity='金', effect='获得1个【折叠小刀】。我方小队获得30%前台强度和5%伤害增幅。'),
    PlazaAugment(id='230301', name='和平手枪祝福', rarity='金', effect='获得1个【和平手枪】。我方小队获得30%后台强度和15初始能量。'),
    PlazaAugment(id='230401', name='生命之花祝福', rarity='金', effect='获得1个【生命之花】。我方小队获得15%生命增幅和5%治疗强度。'),
    PlazaAugment(id='230501', name='量产型装甲祝福', rarity='金', effect='获得1个【量产型装甲】。我方小队获得15%伤害减免和5%护盾强度。'),
    PlazaAugment(id='230601', name='公司军火更新·金', rarity='金', effect='每次进入新节点时，你物品栏里的装备变为同品质的其他装备。获得2件随机简易装备。'),
    PlazaAugment(id='230701', name='回收计划', rarity='金', effect='出售角色时，会将进阶装备拆分成简易装备。获得1件进阶装备，并在5个节点后获得1件随机简易装备。'),
    PlazaAugment(id='230702', name='回收计划+', rarity='金', effect='出售角色时，会将进阶装备拆分成简易装备。获得1件进阶装备，并在4个节点后获得1件随机简易装备。'),
    PlazaAugment(id='230801', name='升级锅炉', rarity='金', effect='对简易装备使用冶金炉会使其变为随机进阶装备，获得2个【冶金炉】。'),
    PlazaAugment(id='230901', name='秘密典籍', rarity='金', effect='获得1个【星徽秘典】，获得8金币。'),
    PlazaAugment(id='230902', name='秘密典籍+', rarity='金', effect='获得1个【星徽秘典】，获得12金币。'),
    PlazaAugment(id='231001', name='全武行', rarity='金', effect='获得1个【武器大师】，【武器大师】额外提供5%幸运一击率，5%幸运一击伤害，5%速度增幅。'),
    PlazaAugment(id='231101', name='这么大的钻石', rarity='金', effect='佩佩携带【财富宝钻】出现，这么大的钻石，送给你！'),
    PlazaAugment(id='231201', name='红钻闪耀', rarity='金', effect='获得1个【红钻】。进入3个节点后，获得【简易武装箱】。'),
    PlazaAugment(id='231301', name='蓝钻闪耀', rarity='金', effect='获得1个【蓝钻】。进入3个节点后，获得【简易武装箱】。'),
    PlazaAugment(id='231401', name='精密拆装·金', rarity='金', effect='获得1个【精密拆装扳手】，1个【冶金炉】和2个随机简易武装。'),
    PlazaAugment(id='231501', name='好运令牌·金', rarity='金', effect='获得1个【好运令牌】和1件随机简易装备。'),
    PlazaAugment(id='231601', name='好运来', rarity='金', effect='合成与获得进阶装备时，改为获得一个【好运令牌】。获得2件随机简易装备。'),
    PlazaAugment(id='231701', name='黄金垃圾', rarity='金', effect='获得一个【金垃圾袋】，它提供大量属性和15金币。'),
    PlazaAugment(id='250101', name='人海战术', rarity='金', effect='我方小队的前/后台强度提高10%。战斗中，我方小队在场的角色与忆灵数量之和大于8时，我方小队的前/后台强度提高20%。'),
    PlazaAugment(id='250201', name='打通上下游·金', rarity='金', effect='我方小队速度增幅提高10%。每个节点开始时，速度增幅额外提高1%。'),
    PlazaAugment(id='250301', name='现金为王', rarity='金', effect='出售场上和备战席的所有角色，之后每场进入战斗时，为我方前台提供护盾，护盾量等同于该次出售角色所获得总金币数*1000。'),
    PlazaAugment(id='250401', name='独狼', rarity='金', effect='若角色不具有已激活的非独立羁绊，使其获得120%前/后台强度和36%伤害减免。'),
    PlazaAugment(id='250501', name='中产阶级', rarity='金', effect='我方小队里每有1位2星角色，使小队获得5%伤害减免和15%前/后台强度。'),
    PlazaAugment(id='250601', name='前段发力', rarity='金', effect='我方小队在进入战斗时行动提前40%，前/后台强度提高60%，每经过1行动值，降低1%，最多降低至0。'),
    PlazaAugment(id='250701', name='三三三', rarity='金', effect='3星/3费/穿戴3件装备的角色，获得10%速度增幅和20%前/后台强度，满足不同条件的效果可叠加。'),
    PlazaAugment(id='250801', name='创伤小组', rarity='金', effect='我方小队伤害增幅提高15%，进入战斗时，生命上限降低30%，受到致命攻击时，行动值惩罚减少20点。'),
    PlazaAugment(id='250901', name='绕口令', rarity='金', effect='进入战斗时，前台一号位角色及其忆灵获得等同于后台一号位角色30%后台强度的前台强度，后台一号位角色及其忆灵获得等同于前台一号位角色30%前台强度的后台强度。'),
    PlazaAugment(id='251001', name='风暴骑士', rarity='金', effect='前台一号位角色获得150%速度增幅。进入战斗时，该角色回合开始时，受到等同于生命上限70%固定数值的风属性附加伤害。'),
    PlazaAugment(id='251101', name='幸运中的幸运', rarity='金', effect='进入战斗时，我方队员幸运一击率若大于20%，则降低至20%，每通过该方式降低1%幸运一击率，使幸运一击伤害提高2%。'),
    PlazaAugment(id='251201', name='榜样的力量·金', rarity='金', effect='战斗中，伤害统计排名第一的队员成为【榜样】，前/后台强度提高40%。其他队员前/后台强度提高10%。'),
    PlazaAugment(id='251301', name='OOTD·金', rarity='金', effect='我方小队每穿戴一件不同的装备，获得3%生命提高，6%前/后台强度。'),
    PlazaAugment(id='251401', name='打人就打脸·金', rarity='金', effect='我方小队幸运一击率提高10%，造成幸运一击伤害后使受击目标陷入【脆弱】：受到的伤害提高30%，持续1回合。'),
    PlazaAugment(id='251501', name='团队力量·金', rarity='金', effect='每有一个已激活的羁绊，小队就会获得6%前/后台强度和4%生命增幅。'),
    PlazaAugment(id='251601', name='钻石恒永久', rarity='金', effect='获得1个【红钻】，角色每携带1件钻石或由钻石合成的装备，在进入新节点时会永久获得3%伤害增幅。'),
    PlazaAugment(id='251801', name='双人舞', rarity='金', effect='上阵的星核猎手数量为2时，激活【猎星人】效果所需攻击数减少1，被激活的攻击造成200%原伤害。获得【千冶·刃】和【卡芙卡】。'),
    PlazaAugment(id='251901', name='读博深造', rarity='金', effect='战斗开始时，若银河学者羁绊处于激活状态，一名随机的1费或2费银河学者变成3星。获得【艾丝妲】和【阮·梅】。'),
    PlazaAugment(id='252001', name='钢铁美学', rarity='金', effect='【造物引擎】造成400%原伤害，但是无法消灭目标。获得【希儿】。'),
    PlazaAugment(id='252101', name='人在旅途', rarity='金', effect='星间旅人若只有3名及以下登场，登场角色额外提供200%的星间旅人属性加成。获得【绯英】和【银枝】。'),
    PlazaAugment(id='252201', name='装备党', rarity='金', effect='激活狼狩羁绊时，狼狩角色们每穿戴一件装备，就获得4%伤害增幅和2%速度增幅。获得【椒丘】和【飞霄】。'),
    PlazaAugment(id='252301', name='梦境大舞台', rarity='金', effect='盛会之星羁绊激活时，战斗中首次激活3/7/10个不同的非独立羁绊后，获得【盛会之星星徽】。获得【花火】。'),
    PlazaAugment(id='252401', name='赞美太阳', rarity='金', effect='每拥有一件【白昼装备】以及其原型装备，在进入新节点时就获得1点经验。角色每穿戴一件【白昼装备】，幸运一击率提高10%。获得【那刻夏】。'),
    PlazaAugment(id='252501', name='月光宝盒', rarity='金', effect='完美通关时，夜之半神获得的【月光精华】提高100%，领取夜之半神奖励时，也会获得一名夜之半神角色，【月色】层数越高，越可能领取到高费角色。获得【赛飞儿】和【万敌】。'),
    PlazaAugment(id='252601', name='借力打力', rarity='金', effect='敌方目标被消灭后，【借力球】的伤害分摊比例永久提高0.15%。获得【黑塔】和【缇宝】。'),
    PlazaAugment(id='252701', name='超充站', rarity='金', effect='能量地块上的单位获得【超级电池】，施放终结技后消耗【超级电池】充满能量。激活3/5/7/10羁绊时，分别获得1/1/2/3层【超级电池】。获得【阿格莱雅】和【藿藿】。'),
    PlazaAugment(id='252801', name='燃起来了', rarity='金', effect='【燃血角斗场】以80%上限开始战斗，且保留的充能提高20%。获得【万敌】和【千冶·刃】。'),
    PlazaAugment(id='252901', name='量子力学', rarity='金', effect='【量子同频】角色累计星数达3/6/9时，额外获得1/2/3层【同频】。获得【希儿】。'),
    PlazaAugment(id='253101', name='星魂升华', rarity='金', effect='本局游戏中，我方前台角色的星魂提高1阶'),
    PlazaAugment(id='253201', name='如有神助', rarity='金', effect='【仙舟】羁绊召唤的【神君】造成120%原伤害。轮次开始时、倒计时归零时，【神君】伤害段数增加10并立即行动。'),
    PlazaAugment(id='253301', name='爆仓', rarity='金', effect='我方小队攻击敌方目标后，若其生命值百分比少于16%，将其【斩杀】。'),
    PlazaAugment(id='253401', name='骇客专家:银狼', rarity='金', effect='获得专家顾问【银狼】，并使其在本局游戏中加入商店。获得1个随机4费骇客改件。'),
    PlazaAugment(id='253501', name='潜行专家:貊泽', rarity='金', effect='获得专家顾问【貊泽】，并使其在本局游戏中加入商店。他上场时不占用团队规模，赋能【雷霆一击】额外造成600%基础伤害。'),
    PlazaAugment(id='253601', name='迷之旅人', rarity='金', effect='激活4【巡海游侠】时，其中3位巡海游侠会发生一次讨论，之后，你获得一个携带着【星间旅人星徽】的2星【黄泉】。进入下一个奖励节点时，获得【波提欧】。'),
    PlazaAugment(id='253701', name='不虚此行', rarity='金', effect='【列车同行】羁绊的【星穹列车】造成300%原伤害，【光轨】增益层数上限提高2层。'),
    PlazaAugment(id='253801', name='离火燎原', rarity='金', effect='【减益】成员攻击时，【离火】的真实伤害效果变为原值的150%，【减益】成员施放终结技时，则变为300%。'),
    PlazaAugment(id='260101', name='摸个鱼吧I', rarity='金', effect='获得专家顾问【青雀】，并使其在本局游戏中加入商店。获得6金币。深思熟虑5个节点后，青雀会想出黄金投资策略！'),
    PlazaAugment(id='260201', name='摸个鱼吧II', rarity='金', effect='获得2个【青雀】和6金币。深思熟虑5个节点后，青雀会想出棱彩投资策略！'),
    PlazaAugment(id='260301', name='加拉赫顾问', rarity='金', effect='获得专家顾问【加拉赫】，并使其在本局游戏中加入商店。获得【生命之花】和4金币。'),
    PlazaAugment(id='260401', name='快请专家·金', rarity='金', effect='获得1个【】，4个节点后，获得2个【员工投影仪】。'),
    PlazaAugment(id='260501', name='停云顾问', rarity='金', effect='获得专家顾问【停云】，并使其在本局游戏中加入商店。获得【光能电池】和4金币。'),
    PlazaAugment(id='260601', name='退化', rarity='金', effect='使最右侧的敌人词缀失效，并使敌人难度-5。获得8金币。'),
    PlazaAugment(id='260701', name='愚者恶作剧', rarity='金', effect='商店中出现的的2/4费卡有20%的概率变为【花火】/【火花】，进入新节点时，备战席的1星【花火】/【火花】会留下2/4金币并去别处找乐子。'),
    PlazaAugment(id='260801', name='战术专家:佩拉', rarity='金', effect='获得专家顾问【佩拉】，并使其在本局游戏中加入商店。小队每有一名不同费用的角色，【佩拉】的终结技就额外降低敌方目标12%防御力。'),
    PlazaAugment(id='260901', name='领航专家:姬子', rarity='金', effect='获得专家顾问【姬子】，并使其在本局游戏中加入商店。战斗开始时，姬子邀请大家品尝咖啡，根据她的星级使我方全体行动提前40%/70%/100%，获得25%/50%/90%速度增幅，所有前台角色损失40%当前生命值。'),
    PlazaAugment(id='300101', name='开源节流', rarity='棱彩', effect='获得10金币，利息上限提升至9。进入新节点时，如果上个节点你没有花费金币，则可获得最大利息的金币数。'),
    PlazaAugment(id='300201', name='商业间谍', rarity='棱彩', effect='购买经验的花费减1，升级时刷新商店，并偷取其中最贵的3个角色。'),
    PlazaAugment(id='300401', name='概率事件', rarity='棱彩', effect='刷新时有45%概率获得一次免费刷新。'),
    PlazaAugment(id='300501', name='天降救兵', rarity='棱彩', effect='获得一个随机3星1费角色，获得1个【简易武装箱】。'),
    PlazaAugment(id='300601', name='被动收入', rarity='棱彩', effect='每次进入新节点时获得经验，数值等同于你备战席最左侧角色的基础费用。'),
    PlazaAugment(id='300701', name='及时雨', rarity='棱彩', effect='获得3个随机2星4费角色和1个【完美投影仪】，获得4次免费刷新。'),
    PlazaAugment(id='300801', name='利息上调', rarity='棱彩', effect='获得25金币。你的最大利息提升至10金币。'),
    PlazaAugment(id='300901', name='买断制', rarity='棱彩', effect='你不再获得利息。即刻获得15金币。每次进入新节点时，获得4经验。'),
    PlazaAugment(id='301001', name='本金充裕', rarity='棱彩', effect='获得26金币。每次进入新节点时，若拥有超过50金币，每额外10金币就会获得1次免费刷新(最多3次)。'),
    PlazaAugment(id='301002', name='本金充裕+', rarity='棱彩', effect='获得45金币。每次进入新节点时，若拥有超过50金币，每额外10金币就会获得1次免费刷新(最多3次)。'),
    PlazaAugment(id='301101', name='节节高升', rarity='棱彩', effect='在你每次升级时获得1个2星角色和1金币。这个角色的费用是你的等级减4(最小值：1费)。'),
    PlazaAugment(id='301201', name='彩虹矿', rarity='棱彩', effect='在下个奖励节点额外获取一个棱彩晶矿，里面装满了丰厚的战利品。'),
    PlazaAugment(id='301202', name='彩虹矿+', rarity='棱彩', effect='在下个奖励节点额外获取一个棱彩晶矿，里面装满了丰厚的战利品。'),
    PlazaAugment(id='301301', name='晋升名额', rarity='棱彩', effect='购买经验时，使商店中的一个随机角色变为高1费的另一个随机角色。'),
    PlazaAugment(id='301401', name='公司严选', rarity='棱彩', effect='现在及每个位面开始时，开启一个由5个独特4费角色组成的商店，并获得3金币。'),
    PlazaAugment(id='301501', name='爆晶矿·彩', rarity='棱彩', effect='我方小队消灭敌方目标时，有45%概率获得一个战利品晶矿。'),
    PlazaAugment(id='301601', name='淘金客', rarity='棱彩', effect='你每次消耗金币刷新商店，都会获得2经验值。'),
    PlazaAugment(id='301701', name='高效决策', rarity='棱彩', effect='获得9999次免费刷新，但是只持续45s。持续时间结束时，移除你所有的免费刷新。'),
    PlazaAugment(id='301801', name='奋斗协议', rarity='棱彩', effect='购买经验值消耗6点小队生命值而非金币。首领战斗结束时回复50点小队生命值。'),
    PlazaAugment(id='301901', name='临时工合约', rarity='棱彩', effect='获得8个【员工投影仪】，进入下个节点时，所有未使用的【员工投影仪】都会消失。'),
    PlazaAugment(id='302001', name='武装突入', rarity='棱彩', effect='遭遇节点的奖励变为2倍。获得2个【简易武装箱】。'),
    PlazaAugment(id='302101', name='黄晶矿工', rarity='棱彩', effect='开启晶矿时，有50%概率获得一个低一档的晶矿，有极低概率获得棱彩晶矿。立刻获得一个黄金晶矿。'),
    PlazaAugment(id='302201', name='黄金投资', rarity='棱彩', effect='立刻进行一次黄金品质投资策略三选一，选择有3次刷新机会。3个节点后，再获得一个。'),
    PlazaAugment(id='302301', name='决议:娱乐星球', rarity='棱彩', effect='你受到的伤害加倍，进入战斗时，若拥有180枚金币，将本局游戏剩余的非首领节点替换为奖励节点。获得50金币。'),
    PlazaAugment(id='302401', name='伟大征服', rarity='棱彩', effect='连胜奖励变为3倍，敌人难度+N，N为你的当前连胜数。获得12经验。'),
    PlazaAugment(id='302501', name='孪生姵姵', rarity='棱彩', effect='获得一个姵姵，它看起来和你的佩佩一模一样！'),
    PlazaAugment(id='302601', name='价值投资·彩', rarity='棱彩', effect='获得1个随机的2星2费角色。每次进入新节点时，获得1星的该角色，补给后额外获得2个，持续至本局游戏结束。'),
    PlazaAugment(id='302701', name='节假日礼盒', rarity='棱彩', effect='获得随机的大笔奖励。'),
    PlazaAugment(id='302801', name='藏一手', rarity='棱彩', effect='我方小队生命值将降低至0时，免疫这次伤害并将生命值变为40点，并获得30点经验和80金币。'),
    PlazaAugment(id='302901', name='控制规模', rarity='棱彩', effect='最大等级变为7级，获得【财富宝钻】和40金币。'),
    PlazaAugment(id='303001', name='星际和平保险', rarity='棱彩', effect='获得等同于你已损失生命数量的金币。战斗后恢复10点小队生命值。'),
    PlazaAugment(id='303101', name='采购专员·彩', rarity='棱彩', effect='每5次刷新，商店会刷出5张费用相同的角色，费用为你备战席最左侧角色的费用。'),
    PlazaAugment(id='303201', name='金币大使叽米', rarity='棱彩', effect='超稀有的叽米登场！爆出超多金币！！'),
    PlazaAugment(id='303301', name='星徽大使叽米', rarity='棱彩', effect='超稀有的叽米登场！爆出超多星徽！！'),
    PlazaAugment(id='303401', name='偶像经济', rarity='棱彩', effect='获得【火花】和一个【火花礼盒】，倒计时10个节点后礼盒打开，提供大量奖励！战斗完胜时，额外减少1点倒计时。'),
    PlazaAugment(id='303501', name='武器批发商', rarity='棱彩', effect='下个首领节点后，获得所有类型的简易装备各1个。'),
    PlazaAugment(id='303601', name='远见', rarity='棱彩', effect='获得一个随机黄金投资策略和15金币。后续的投资策略节点改为获得随机1个棱彩投资策略（无法刷新），并且不增加敌人难度。'),
    PlazaAugment(id='303701', name='搜打撤', rarity='棱彩', effect='每当你进入新节点时，获得1次免费刷新。通关下一个首领节点后，获得等同于场上和备战席所有角色价值的金币。'),
    PlazaAugment(id='303801', name='不等价交换', rarity='棱彩', effect='交换你的小队生命值和金币。'),
    PlazaAugment(id='303901', name='着眼当下', rarity='棱彩', effect='你购买的下一个1/2/3/4/5费角色变成2星，随后，将其从商店中移除。立即获得5金币。'),
    PlazaAugment(id='304001', name='狸财经狸', rarity='棱彩', effect='获得1个【狸狸】，它带着初始资金30【金币】来帮你理财，每回合获得利息+2金币。当你的金币少于20时，从狸狸那里取出10金币存款。进入第三位面首领节点时，取出所有存款。\\n\\n一个月内花光十个亿，你就可以继承狸的财产！。'),
    PlazaAugment(id='304101', name='龙虎兄弟狸', rarity='棱彩', effect='获得【狸小龙】和【狸小虎】和2个【简易武装箱】，它们都穿着【随便骰子】，进入新节点时，它们的装备和我方角色穿戴的装备每有一件相同，就使你获得4金币。\\n\\n同名装备只计算1次，你的【随便骰子】本身一定能和狸狸的【随便骰子】配对！。'),
    PlazaAugment(id='304201', name='狸狸的早晨', rarity='棱彩', effect='获得7个【狸狸】，进入新节点时，随机给这些狸狸员工穿戴2个随机星徽。'),
    PlazaAugment(id='304301', name='大变活狸', rarity='棱彩', effect='你最右边的3个【狸狸】重新随机星徽，获得2个【星徽秘典】。'),
    PlazaAugment(id='310101', name='列车同行星徽套组', rarity='棱彩', effect='获得1个【列车同行星徽】，和1个【丹恒·饮月】，以及1个【高周波电锯】。'),
    PlazaAugment(id='310301', name='银河学者星徽套组', rarity='棱彩', effect='获得1个【银河学者星徽】，和1个【艾丝妲】，以及1个【胜利之旗】。'),
    PlazaAugment(id='310501', name='贝洛伯格星徽套组', rarity='棱彩', effect='获得1个【贝洛伯格星徽】，和1个【希儿】，以及1个【武器大师】。'),
    PlazaAugment(id='310601', name='星间旅人星徽套组', rarity='棱彩', effect='获得1个【星间旅人星徽】，和1个【银枝】，以及1个【永动机】。'),
    PlazaAugment(id='310701', name='仙舟星徽套组', rarity='棱彩', effect='获得1个【仙舟星徽】，和1个【藿藿】，以及1个【生命之环】。'),
    PlazaAugment(id='310801', name='狼狩星徽套组', rarity='棱彩', effect='获得1个【狼狩星徽】，和1个【椒丘】，以及1个【生命之环】。'),
    PlazaAugment(id='311001', name='盛会之星星徽套组', rarity='棱彩', effect='获得1个【盛会之星星徽】，和1个【花火】，以及1个【信心注入器】。'),
    PlazaAugment(id='311101', name='昼之半神星徽套组', rarity='棱彩', effect='获得1个【昼之半神星徽】，和1个【风堇】，以及1个【生命之环】。'),
    PlazaAugment(id='311201', name='夜之半神星徽套组', rarity='棱彩', effect='获得1个【夜之半神星徽】，和1个【万敌】，以及1个【杀红眼】。'),
    PlazaAugment(id='320101', name='追击星徽套组', rarity='棱彩', effect='获得1个【追击星徽】，和1个【飞霄】，以及1个【永动机】。'),
    PlazaAugment(id='320201', name='击破星徽套组', rarity='棱彩', effect='获得1个【击破星徽】，和1个【阮·梅】，以及1个【流星飞翼】。'),
    PlazaAugment(id='320301', name='群攻星徽套组', rarity='棱彩', effect='获得1个【群攻星徽】，和1个【翡翠】，以及1个【反卫星狙击枪】。'),
    PlazaAugment(id='320401', name='能量星徽套组', rarity='棱彩', effect='获得1个【能量星徽】，和1个【星期日】，以及1个【胜利之旗】。'),
    PlazaAugment(id='320501', name='治疗星徽套组', rarity='棱彩', effect='获得1个【治疗星徽】，和1个【风堇】，以及1个【生命之环】。'),
    PlazaAugment(id='320601', name='燃血星徽套组', rarity='棱彩', effect='获得1个【燃血星徽】，和1个【万敌】，以及1个【杀红眼】。'),
    PlazaAugment(id='320701', name='减益星徽套组', rarity='棱彩', effect='获得1个【减益星徽】，和1个【黄泉】，以及1个【高周波电锯】。'),
    PlazaAugment(id='320801', name='持续伤害星徽套组', rarity='棱彩', effect='获得1个【持续伤害星徽】，和1个【卡芙卡】，以及1个【反重力皮靴】。'),
    PlazaAugment(id='320901', name='量子同频星徽套组', rarity='棱彩', effect='获得1个【量子同频星徽】，和1个【希儿】，以及1个【反重力皮靴】。'),
    PlazaAugment(id='321001', name='护盾星徽套组', rarity='棱彩', effect='获得一个【护盾星徽】，和1个【砂金】，以及1个【自适应外骨骼】。'),
    PlazaAugment(id='321101', name='战技点星徽套组', rarity='棱彩', effect='获得1个【战技点星徽】，和1个【丹恒·饮月】，以及1个【高周波电锯】。'),
    PlazaAugment(id='330101', name='优势火力论', rarity='棱彩', effect='获得1个【特权赋予卡】和1个【简易武装箱】。'),
    PlazaAugment(id='330201', name='财富就是力量', rarity='棱彩', effect='获得1个【财富宝钻】，该装备额外提供30%前/后台强度和20%速度增幅。'),
    PlazaAugment(id='330301', name='复印件', rarity='棱彩', effect='获得一个已经拥有的星徽的复制，获得24点经验。'),
    PlazaAugment(id='330401', name='客制化服务', rarity='棱彩', effect='【随便骰子】会为你的角色随机出其推荐列表中的装备。获得3个【幸运星】。'),
    PlazaAugment(id='330501', name='军备供应链', rarity='棱彩', effect='获得1个【简易武装箱】，接下来5个节点开始时，获得1个【简易武装箱】。'),
    PlazaAugment(id='330601', name='公司军火更新·彩', rarity='棱彩', effect='每次进入新节点时，物品栏里的装备变为同品质的其他装备。\xa0获得1件随机特权装备。'),
    PlazaAugment(id='330701', name='手枪发烧友', rarity='棱彩', effect='获得5个【和平手枪】。【和平手枪】提供5%幸运一击率。'),
    PlazaAugment(id='330801', name='多元化团队', rarity='棱彩', effect='获得2个【财富宝钻】，你的羁绊最多只能激活到4人口对应的效果。'),
    PlazaAugment(id='330901', name='终身学习', rarity='棱彩', effect='现在以及每个位面开始时，获得【星徽秘典】。'),
    PlazaAugment(id='331001', name='佩佩客串', rarity='棱彩', effect='佩佩闪亮登场！每完美通关一个战斗节点，佩佩就会穿戴一件进阶装备，进入5个节点后，阿兰接走佩佩们并留下所有装备。'),
    PlazaAugment(id='331101', name='装备方案A', rarity='棱彩', effect='获得【光速螺旋桨】、【反重力皮靴】和【折叠小刀】。'),
    PlazaAugment(id='331201', name='装备方案B', rarity='棱彩', effect='获得【冷笑话引擎】、【永动机】和【和平手枪】。'),
    PlazaAugment(id='331301', name='入职礼包', rarity='棱彩', effect='进入战斗时：携带了2件装备的至多4个角色会获得一件处在推荐列表中的随机进阶装备。'),
    PlazaAugment(id='331401', name='独家代言', rarity='棱彩', effect='从3件进阶装备中选择一件获取。本局游戏中，你获得组成该装备的简易装备时，改为获得该进阶装备。'),
    PlazaAugment(id='331501', name='精密拆装·彩', rarity='棱彩', effect='获得1个【精密拆装扳手】和1个【随便骰子·特权】。'),
    PlazaAugment(id='331601', name='好运令牌·彩', rarity='棱彩', effect='获得1个【好运令牌】。每累计进入4个节点后，获得1个【好运令牌】。'),
    PlazaAugment(id='331701', name='全都要·彩', rarity='棱彩', effect='本局游戏中，补给阶段的可选项减少2个。补给阶段选择后，额外获得所有未选择的角色及装备。'),
    PlazaAugment(id='331801', name='分解万物', rarity='棱彩', effect='获得一个【物质分解液】，本局游戏中，你的所有进阶装备变成【物质分解液】。它将额外造成3次伤害，对普通/精英及首领敌人分别造成2%/1%生命上限百分比的真实伤害，并使我方小队获得4%伤害减免。'),
    PlazaAugment(id='331901', name='完美进化', rarity='棱彩', effect='获得一个【战场进化手册】，进入战斗时，穿戴【战场进化手册】的1星角色会变为2星。4个节点后，获得一个【战场进化手册】。'),
    PlazaAugment(id='332001', name='脱颖而出', rarity='棱彩', effect='穿戴3件装备的角色在进入战斗时，会将其中随机一件变为特权装备，持续到战斗结束。'),
    PlazaAugment(id='332101', name='数值碾压', rarity='棱彩', effect='角色穿戴的简易装备额外提供8倍的基础属性。获得2件随机简易装备。'),
    PlazaAugment(id='332201', name='轮回不止', rarity='棱彩', effect='获得【白厄】和一件【轮回者】装备。进入第二/三位面时，再获得一次。\\n\\n\\n本局游戏结束时，【白厄】携带着装备成为新的【轮回者】。\\n若游戏结束时【白厄】不在队伍中，【轮回者】的装备变为初始状态。'),
    PlazaAugment(id='332301', name='融合召唤', rarity='棱彩', effect='给角色穿戴2件相同进阶装备时，它们会合成为对应的特权装备。获得1个【简易武装箱】。'),
    PlazaAugment(id='332401', name='环保大使叽米', rarity='棱彩', effect='获得超稀有的叽米！！获得超多【金垃圾袋】！！'),
    PlazaAugment(id='350101', name='幸运之子', rarity='棱彩', effect='我方小队幸运一击率提高25%。进入战斗时，我方小队中幸运一击率达到100%的角色，自身与忆灵幸运一击伤害提高40%。'),
    PlazaAugment(id='350301', name='超光速提拔', rarity='棱彩', effect='战斗开始时：1个随机的1费角色在这场战斗中升为4星，并获得5%前/后台强度。'),
    PlazaAugment(id='350401', name='战术义眼', rarity='棱彩', effect='我方小队消灭普通/精英及首领敌人时，恢复25%/75%能量。'),
    PlazaAugment(id='350402', name='战术义眼+', rarity='棱彩', effect='我方小队消灭普通/精英及首领敌人时，恢复25%/75%能量。获得1个【简易武装箱】。'),
    PlazaAugment(id='350403', name='战术义眼++', rarity='棱彩', effect='我方小队消灭普通/精英及首领敌人时，恢复25%/75%能量。获得1个【进阶武装箱】。'),
    PlazaAugment(id='350501', name='榜样的力量·彩', rarity='棱彩', effect='战斗中，伤害统计排名第一的队员成为【榜样】，前/后台强度提高70%。其他队员施放攻击后，对攻击目标造成等同于【榜样】累计伤害1%的真实伤害。'),
    PlazaAugment(id='350601', name='佩佩驾到', rarity='棱彩', effect='获得1个携带着3个永久附着星徽的【佩佩】。获得8金币。'),
    PlazaAugment(id='350701', name='万箭齐发', rarity='棱彩', effect='战斗开始时，发射风箭攻击随机敌方目标，箭矢数量等同于小队总星数+8，每根风箭造成等同于1600%基础伤害的风属性伤害。'),
    PlazaAugment(id='350801', name='后勤超响应', rarity='棱彩', effect='角色的后台强度提高，其数值等同于后台总星数×12%。'),
    PlazaAugment(id='350901', name='三五成群', rarity='棱彩', effect='后台角色数量达到3名/5名及以上时，你的小队获得5%/30%速度增幅和10%/50%前/后台强度。'),
    PlazaAugment(id='351001', name='基本保障', rarity='棱彩', effect='至少携带1件装备的角色获得20%生命增幅和16%伤害增幅。'),
    PlazaAugment(id='351101', name='更快,更幸运', rarity='棱彩', effect='进入战斗时，速度最高的角色及其忆灵速度增幅提高8%，幸运一击率提高12%。每经过20行动值，在另一名我方角色上重复此效果。'),
    PlazaAugment(id='351201', name='鲜血阶梯', rarity='棱彩', effect='获得【斩首行动】。我方队员每消灭一名精英/首领敌人，我方小队在本局伤害增幅永久提高8%。'),
    PlazaAugment(id='351301', name='打通上下游·彩', rarity='棱彩', effect='我方小队获得15%前/后台强度，每次进入新节点时，该加成提高3%。'),
    PlazaAugment(id='351401', name='野蛮成长', rarity='棱彩', effect='战斗开始时，随机两名前台角色获得100%前台强度提高，随机两名后台角色获得100%后台强度提高。'),
    PlazaAugment(id='351501', name='保守派', rarity='棱彩', effect='我方小队获得8%伤害减免。进入战斗时，生命上限最低的角色额外获得12%伤害减免。获得一件【进阶武装箱】。'),
    PlazaAugment(id='351601', name='攻防一体', rarity='棱彩', effect='我方小队获得25%伤害减免，且获得等同于伤害减免的伤害增幅。'),
    PlazaAugment(id='351701', name='幸运闪避EX', rarity='棱彩', effect='我方小队获得25%幸运一击率，受到敌人攻击时，有等同于30%幸运一击率的概率使受到的伤害变为1。'),
    PlazaAugment(id='351801', name='羁绊的力量', rarity='棱彩', effect='每有一个已激活的非独立羁绊，小队就会获得5%伤害增幅和3%伤害减免。'),
    PlazaAugment(id='351901', name='定点爆破', rarity='棱彩', effect='每个波次开始时，【重锤】立即对当前生命值最高的敌人造成999999%基础伤害，最多对首领敌人造成50%生命上限的伤害。'),
    PlazaAugment(id='352101', name='乱成一锅粥', rarity='棱彩', effect='每次进入新节点时，处在备战席最左侧6个位置的角色变为随机的同费用角色。立刻获得5次免费刷新和10金币。'),
    PlazaAugment(id='352102', name='乱成一锅粥+', rarity='棱彩', effect='每次进入新节点时，处在备战席最左侧6个位置的角色变为随机的同费用角色。立刻获得7次免费刷新和14金币。'),
    PlazaAugment(id='352201', name='白衣伙伴', rarity='金', effect='你的【白厄】/【星期日】可以互相用于升星。首次获得3星【白厄】/【星期日】之一时，立即获得另一个的3星版本。获得【白厄】，3个节点后获得【星期日】。\\n\\n升星结果取决于较多的那一方。比如，2星【白厄】+2星【白厄】+2星【星期日】=3星【白厄】。'),
    PlazaAugment(id='352301', name='双龙会', rarity='金', effect='你的【丹恒·饮月】/【丹恒·腾荒】可以互相用于升星。首次获得3星【丹恒·饮月】/【丹恒·腾荒】之一时，立即获得另一个的3星版本。获得【丹恒·腾荒】、【丹恒·饮月】。\\n\\n升星结果取决于较多的那一方。比如，2星【丹恒·饮月】+2星【丹恒·腾荒】+2星【丹恒·腾荒】=3星【丹恒·腾荒】。'),
    PlazaAugment(id='352401', name='盗用身份', rarity='棱彩', effect='进入第二位面的首领节点时，获得一个穿着2个【动能激发剑】和【列车同行星徽】的【火花】和1个【{NICKNAME}】。'),
    PlazaAugment(id='352501', name='本姑娘就是罗刹', rarity='棱彩', effect='获得2星【三月七】。每次进入新节点时，获得【三月七】。进入战斗前，这位姑娘化身【罗刹】。战斗中，她会「治疗」敌方目标，造成等同于（200+2.0*后台强度）%的基础伤害，每有100后台强度，还可在「急救」时造成2%最大生命值的真实伤害。\\n\\n现在，本姑娘就是罗刹！'),
    PlazaAugment(id='352601', name='黑塔纪元', rarity='棱彩', effect='获得【大黑塔】并将216张【黑塔】加入商店，你获得3星【黑塔】时获得【大黑塔】，且商店能继续刷新【黑塔】。出战时，你拥有的【黑塔】们每有1总金币价值，都使【黑塔】们追击时额外转一圈。你拥有的【黑塔】们每有1总金币价值，使【黑塔】/【大黑塔】获得10%前后台强度。'),
    PlazaAugment(id='352701', name='飞光·映月', rarity='棱彩', effect='获得【镜流】和特殊的1费【景元】，他们获得【师徒】羁绊。【镜流】2星时，【景元】变为3费。【镜流】3星时，【景元】变为你认识的5费【景元】。'),
    PlazaAugment(id='352702', name='飞光·传剑', rarity='棱彩', effect='获得【彦卿】和【景元】，他们获得【师徒】羁绊。【彦卿】的【天河泻】获得强化，造成战斗中【仙舟】神君和【景元】累计伤害值15%的伤害。两人同时在场上时，每进入一个新节点该值提高4%。'),
    PlazaAugment(id='352801', name='都是这家伙的错！', rarity='棱彩', effect='获得【命运圣杯星徽】和10金币。若未完美通关战斗且有携带【命运圣杯星徽】的角色参与战斗，视为完美通关并出售1名携带【命运圣杯星徽】的上场角色，可生效3次。\\n\\n“怪我咯？”'),
    PlazaAugment(id='360101', name='摸个鱼吧III', rarity='棱彩', effect='摸到了！获得18个【青雀】和2个【好运令牌】！'),
    PlazaAugment(id='360201', name='快请专家·彩', rarity='棱彩', effect='获得2个【】，1个【好运令牌】和1个【进阶武装箱】。'),
    PlazaAugment(id='360301', name='琼玉专家:青雀', rarity='棱彩', effect='获得装备着3个随机星徽的专家顾问【青雀】，并使其在本局游戏中加入商店。获得2个【冶金炉】。'),
    PlazaAugment(id='360401', name='贸易专家:停云', rarity='棱彩', effect='获得专家顾问【停云】，并使其在本局游戏中加入商店。并获得4个【简易武装箱】、【精密拆装扳手】和10金币。'),
    PlazaAugment(id='360501', name='调饮专家:加拉赫', rarity='棱彩', effect='获得装备着【绝对热量】的专家顾问【加拉赫】，并使其在本局游戏中加入商店。加拉赫行动时，为我方全体恢复3点能量并触发【绝对热量】的生命回复效果。'),
    PlazaAugment(id='360601', name='锻冶专家:刃', rarity='棱彩', effect='获得专家顾问【刃】，并使其在本局游戏中加入商店。在【刃】的装备栏中合成进阶装备时，将其变为特权装备，该效果可生效1次。【刃】在场上或备战席时，每获得10件任意装备，额外可生效一次。'),
)

PLAZA_PORTALS: tuple[PlazaPortal, ...] = (
    PlazaPortal(id='101', name='火药味', effect='开局时获得2个简易武装箱。'),
    PlazaPortal(id='102', name='特权阶级', effect='第二位面开始时，获得1个特权武装箱。'),
    PlazaPortal(id='103', name='增发货币', effect='第一/二/三位面开始时，获得一个6/8/12金币的晶矿。'),
    PlazaPortal(id='104', name='深井角斗场', effect='本局首次达成5连胜时，获得【财富宝钻】。'),
    PlazaPortal(id='105', name='经济过热', effect='本局的全部奖励节点替换为次元扑满主题，次元扑满会掉落更多战利品。'),
    PlazaPortal(id='106', name='二手市场', effect='商店刷新20次后，获得30金币和【员工投影仪】。'),
    PlazaPortal(id='107', name='人身意外险', effect='所有首领节点前都加入一个额外补给阶段。'),
    PlazaPortal(id='108', name='过剩经费', effect='补给阶段中，角色会携带两件装备。'),
    PlazaPortal(id='109', name='人才引进', effect='开局拥有1个随机4费角色。'),
    PlazaPortal(id='110', name='彩虹时代', effect='这局的投资策略均为棱彩品质。'),
    PlazaPortal(id='111', name='黄金时代', effect='这局的投资策略均为黄金品质。'),
    PlazaPortal(id='112', name='白银时代', effect='这局的投资策略均为白银品质，因此敌人难度不会由于选择高品质投资策略而提高。'),
    PlazaPortal(id='113', name='蓝海', effect='进入到一个随机投资环境中，开局额外获得6金币。'),
    PlazaPortal(id='114', name='轮岗', effect='备战阶段开始时，使一个随机费用的刷新概率翻倍，每个备战阶段重新随机。'),
    PlazaPortal(id='115', name='三星佩佩', effect='获得一个穿戴三个随机星徽的佩佩。'),
    PlazaPortal(id='116', name='粗星佩佩', effect='获得一个穿戴三个随机星徽的佩佩，粗心的佩佩有时候会把星徽落在你的物品栏。'),
    PlazaPortal(id='117', name='战争边疆', effect='第三位面的所有战斗节点都替换为遭遇节点。'),
    PlazaPortal(id='118', name='劳务派遣合同', effect='获得随机星徽，每次进入首领节点时，获得对应羁绊的随机角色。'),
    PlazaPortal(id='119', name='经济严重过热', effect='本局的全部奖励节点替换为超级次元扑满主题！超级次元扑满会掉落超多战利品！！但它们跑得超快！！！'),
    PlazaPortal(id='120', name='长线利好', effect='花费金币进行30次刷新后，获得20金币，之后在本局游戏中，只需要1金币就能刷新。'),
    PlazaPortal(id='121', name='人才下沉', effect='商店中有概率出现2星角色。'),
    PlazaPortal(id='122', name='联席决策', effect='在2-6节点进行一次额外的投资策略三选一。'),
    PlazaPortal(id='123', name='头彩', effect='第一个投资策略是棱彩品质。'),
    PlazaPortal(id='124', name='尾彩', effect='第三个投资策略是棱彩品质。'),
    PlazaPortal(id='125', name='量子同频契约', effect='花火和缇宝升星时，随机获得【符玄】或【希儿】。'),
    PlazaPortal(id='126', name='公司契约', effect='获得【翡翠】和【砂金】，累计获得40利息后，获得【托帕&账账】。'),
    PlazaPortal(id='127', name='持续伤害契约', effect='获得【椒丘】和【卡芙卡】。敌人被消灭时，每陷入一个不同的持续伤害状态，获得1点计数。计数达到180时，获得【黑天鹅】。'),
    PlazaPortal(id='128', name='战技点契约', effect='获得【丹恒·饮月】和【花火】。打开20个晶矿后，获得【火花】和1个随机战技点羁绊角色；之后每打开10个晶矿，都可重复获得一次角色奖励。'),
    PlazaPortal(id='129', name='星核猎手契约', effect='获得【卡芙卡】。当【刃】或【千冶·刃】、【卡芙卡】、【银狼LV.999】或【银狼】一起参与一次战斗后，获得【流萤】，在2个节点后才能将其上场。'),
    PlazaPortal(id='131', name='红钻贵族', effect='开局时拥有【红钻】和一个【简易武装箱】。'),
    PlazaPortal(id='132', name='蓝钻贵族', effect='开局时拥有【蓝钻】和一个【简易武装箱】。'),
    PlazaPortal(id='133', name='英雄登场', effect='获得1个2星5费角色，19个节点后才能将其上场。战斗完胜后，上场节点额外提前1点。'),
    PlazaPortal(id='134', name='命运礼物', effect='立刻获得一个【惊喜盒】，倒计时12个节点后礼盒打开，战斗完胜后，倒计时额外减少1点。'),
    PlazaPortal(id='135', name='银·金·彩', effect='本局在固定节点进行投资策略选择时，左、中、右的选项分别为银金彩品质，并且投资策略刷新次数+2。'),
    PlazaPortal(id='136', name='战力提升', effect='获得1个随机2星1费的输出角色，进入新节点时，这位角色永久获得随机属性加成。'),
    PlazaPortal(id='137', name='战力飙升', effect='获得1个随机2星2费角色，进入新节点时，这位角色永久获得随机属性加成。'),
    PlazaPortal(id='138', name='成功经验', effect='在你升到8级后，进入接下来3个节点时，获得12经验。'),
    PlazaPortal(id='139', name='专家研讨会', effect='获得1个【专家邀请函】和1个【简易武装箱】。'),
    PlazaPortal(id='141', name='特邀专家:停云', effect='获得专家顾问【停云】，并使其在本局游戏中加入商店。停云施放终结技时，使目标队员获得等同于停云60%后台强度的前台强度，该效果仅对最新目标队员生效。'),
    PlazaPortal(id='142', name='特邀专家:加拉赫', effect='获得专家顾问【加拉赫】，并使其在本局游戏中加入商店。激活2/4/6/9击破羁绊时，获得1件【以太钻头】。'),
    PlazaPortal(id='143', name='特邀专家:银狼', effect='当你首次获得【银狼LV.999】时，获得专家顾问【银狼】，并使其在本局游戏中加入商店。'),
    PlazaPortal(id='144', name='人才储备', effect='开局补给替换为3个随机3费角色。3费角色升至2/3星时，获得11%/33%速度增幅、22%/66%伤害增幅。'),
    PlazaPortal(id='145', name='进化算法', effect='进入新节点时，所有场上角色获得4%前后台强度和2%伤害减免，该效果可叠加。'),
    PlazaPortal(id='146', name='敌后破坏', effect='开局时，使一个已生成的敌人词缀失效。'),
    PlazaPortal(id='147', name='策略大师', effect='获取投资策略时，获得（2*已拥有投资策略数）的金币。在3-5节点额外获得一个投资策略。'),
    PlazaPortal(id='148', name='特邀专家:桑博', effect='获得专家顾问【桑博】，并使其在本局游戏中加入商店。进入新节点时，老桑博会给你带来小礼物！登场的【桑博】星级越高，礼物越好！'),
    PlazaPortal(id='1001', name='追击概念股', effect='开局时获得【追击】角色和初始简易装备，【追击】角色的刷新概率提高。'),
    PlazaPortal(id='1002', name='燃血概念股', effect='开局时获得【燃血】角色和初始简易装备，【燃血】角色的刷新概率提高。'),
    PlazaPortal(id='1003', name='能量概念股', effect='开局时获得【能量】角色和初始简易装备，【能量】角色的刷新概率提高。'),
    PlazaPortal(id='1004', name='列车同行概念股', effect='开局时获得【列车同行】角色和初始简易装备，【列车同行】角色的刷新概率提高。'),
    PlazaPortal(id='1005', name='银河学者概念股', effect='开局时获得【银河学者】角色和初始简易装备，【银河学者】角色的刷新概率提高。'),
    PlazaPortal(id='1006', name='贝洛伯格概念股', effect='开局时获得【贝洛伯格】角色和初始简易装备，【贝洛伯格】角色的刷新概率提高。'),
    PlazaPortal(id='1007', name='星间旅人概念股', effect='开局时获得【星间旅人】角色和初始简易装备，【星间旅人】角色的刷新概率提高。'),
    PlazaPortal(id='1008', name='仙舟概念股', effect='开局时获得【仙舟】角色和初始简易装备，【仙舟】角色的刷新概率提高。'),
    PlazaPortal(id='1009', name='狼狩概念股', effect='开局时获得【狼狩】角色和初始简易装备，【狼狩】角色的刷新概率提高。'),
    PlazaPortal(id='1010', name='昼之半神概念股', effect='开局时获得【昼之半神】角色和初始简易装备，【昼之半神】角色的刷新概率提高。'),
    PlazaPortal(id='1011', name='夜之半神概念股', effect='开局时获得【夜之半神】角色和初始简易装备，【夜之半神】角色的刷新概率提高。'),
    PlazaPortal(id='1012', name='击破概念股', effect='开局时获得【击破】角色和初始简易装备，【击破】角色的刷新概率提高。'),
    PlazaPortal(id='1013', name='群攻概念股', effect='开局时获得【群攻】角色和初始简易装备，【群攻】角色的刷新概率提高。'),
    PlazaPortal(id='1014', name='减益概念股', effect='开局时获得【减益】角色和初始简易装备，【减益】角色的刷新概率提高。'),
    PlazaPortal(id='1016', name='战技点概念股', effect='开局时获得【战技点】角色和初始简易装备，【战技点】角色的刷新概率提高。'),
    PlazaPortal(id='1101', name='列车同行邀请', effect='获得一个【列车同行星徽】。'),
    PlazaPortal(id='1102', name='银河学者邀请', effect='获得一个【银河学者星徽】。'),
    PlazaPortal(id='1103', name='贝洛伯格邀请', effect='获得一个【贝洛伯格星徽】。'),
    PlazaPortal(id='1104', name='星间旅人邀请', effect='获得一个【星间旅人星徽】。'),
    PlazaPortal(id='1105', name='仙舟邀请', effect='获得一个【仙舟星徽】。'),
    PlazaPortal(id='1106', name='狼狩邀请', effect='获得一个【狼狩星徽】。'),
    PlazaPortal(id='1107', name='盛会之星邀请', effect='获得一个【盛会之星星徽】。'),
    PlazaPortal(id='1108', name='昼之半神邀请', effect='获得一个【昼之半神星徽】。'),
    PlazaPortal(id='1109', name='夜之半神邀请', effect='获得一个【夜之半神星徽】。'),
    PlazaPortal(id='1110', name='追击邀请', effect='获得一个【追击星徽】。'),
    PlazaPortal(id='1111', name='击破邀请', effect='获得一个【击破星徽】。'),
    PlazaPortal(id='1112', name='群攻邀请', effect='获得一个【群攻星徽】。'),
    PlazaPortal(id='1113', name='能量邀请', effect='获得一个【能量星徽】。'),
    PlazaPortal(id='1114', name='燃血邀请', effect='获得一个【燃血星徽】。'),
    PlazaPortal(id='1115', name='减益邀请', effect='获得一个【减益星徽】。'),
    PlazaPortal(id='1116', name='持续伤害邀请', effect='获得一个【持续伤害星徽】。'),
    PlazaPortal(id='1117', name='量子同频邀请', effect='获得一个【量子同频星徽】。'),
    PlazaPortal(id='1118', name='战技点邀请', effect='获得一个【战技点星徽】。'),
    PlazaPortal(id='1119', name='欢愉邀请', effect='获得一个【欢愉星徽】。'),
    PlazaPortal(id='1120', name='命运圣杯邀请', effect='获得1个【命运圣杯星徽】。'),
    PlazaPortal(id='1201', name='欢愉契约', effect='获得【银狼LV.999】，她每次触发独立羁绊【头号玩家】选项时，获得【火花】或【开拓者·欢愉】。'),
    PlazaPortal(id='1202', name='命运圣杯契约', effect='获得【远坂凛】、【吉尔伽美什】，完成两次圣杯试炼后，获得【Archer】。'),
)


def augments_by_id() -> dict[str, PlazaAugment]:
    """id → 条目。"""
    return {a.id: a for a in PLAZA_AUGMENTS}


def portals_by_id() -> dict[str, PlazaPortal]:
    """id → 条目。"""
    return {p.id: p for p in PLAZA_PORTALS}
